quarkus:
  package:
    output-name: "hwcwm-meetup"

  http:
    port: 8080
    root-path: "/"

  swagger-ui:
    always-include: true

  datasource:
    db-kind: "postgresql"
    username: "hwcwm"
    password: "hwcwm"
    jdbc:
      url: "jdbc:postgresql://localhost:5432/hwcwm"

  hibernate-orm:
    sql-load-script: "db/init.sql"
    database:
      generation: "drop-and-create"

